### ISSUE TITLE
Eero Connection Failure

### ISSUE THREAD

**Issue by cireflow** [jrlucier/eero_tracker#22]
I have been running eero_tracker for over a year with no issues even during migration period.  Today the below started and i have tried uninstall/reinstall including new eero.session file and cannot solve this.  

HA version 108.4
eero_tracker version 1.0.6 via HACS 

Eero connection failure: error.session.invalid

Logger: custom_components.eero_tracker.device_tracker
Source: custom_components/eero_tracker/device_tracker.py:95

2020-04-14 19:27:54 ERROR (SyncWorker_7) [custom_components.eero_tracker.device_tracker] Eero connection failure: error.session.invalid
2020-04-14 19:27:54 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/setup.py", line 161, in async_device_tracker_scan
    found_devices = await scanner.async_scan_devices()
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 482, in async_scan_devices
    return await self.hass.async_add_job(self.scan_devices)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eero_tracker/device_tracker.py", line 95, in scan_devices
    self._update_info()
  File "/config/custom_components/eero_tracker/device_tracker.py", line 114, in _update_info
    for network in self.__account['networks']['data']:

Any help would be much appreciated.

BTW...awesome addon

Eric

**Comment by rsnodgrass** [comment]
Which version are you running?
  

  
  

  
  
>

**Comment by rsnodgrass** [comment]
The key error I believe is this:
  

  
 Eero connection failure: error.session.invalid
  
  
  
 Are you sure the eero.session was deleted and then replaced while Home Assistant was shut down?    
  

  
  

  
  
>

**Comment by cireflow** [comment]
Ooops...Apparently not...ughh.  So sorry to bother you.  Thank you for your help.
