### ISSUE TITLE
No devices appearing after installation + restart

### ISSUE THREAD

**Issue by sbressler** [jrlucier/eero_tracker#23]
Hi there, excited to try out this functionality. Wondering if you or @rsnodgrass can help me figure out what I'm doing wrongly. I installed this integration with HACS and then generated `eero.session` on another computer and copied the file contents over to `/config/eero.session` on my RPi and restarted Home Assistant.

Where would I find logs output so I can dig deeper into why 20+ minutes later no new entities were added? I've checked Logbook, Developer Tools -> Logs, and even Supervisor -> System -> System log. Don't see any mention of eero. I imagine I need to change the log level?

Thanks so much!

**Comment by sbressler** [comment]
I just set my log level default in `configuration.yaml` to debug. I now see these seemingly relevant log lines showing something is working but maybe not everything?
```bash
2020-05-04 02:00:54 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for eero_tracker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-04 02:00:55 DEBUG (SyncWorker_5) [custom_components.eero_tracker.device_tracker] Initializing eero_tracker (domain device_tracker)
2020-05-04 02:00:55 DEBUG (zeroconf-ServiceBrowser__hap._tcp.local.) [homeassistant.components.zeroconf] Discovered new device Living Room eero Pro._hap._tcp.local. {'host': '192.168.7.1', 'port': <snip>, 'hostname': 'eero-<snip:mac-address>.local.', 'type': '_hap._tcp.local.', 'name': 'Living Room eero Pro._hap._tcp.local.', 'properties': {'_raw': {'c#': b'12', 'ff': b'2', 'id': b'<snip:mac-address>', 'md': b'eero Pro', 'pv': b'1.1', 's#': b'1', 'sf': b'1', 'ci': b'33', 'sh': b'<snip>'}, 'c#': '12', 'ff': '2', 'id': '<snip:mac-address>', 'md': 'eero Pro', 'pv': '1.1', 's#': '1', 'sf': '1', 'ci': '33', 'sh': '<snip>'}}
2020-05-04 02:00:55 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/setup.py", line 64, in async_setup_legacy
    self.platform.get_scanner, hass, {DOMAIN: self.config}
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eero_tracker/device_tracker.py", line 43, in get_scanner
    return EeroDeviceScanner(hass, config[DOMAIN])
  File "/config/custom_components/eero_tracker/device_tracker.py", line 75, in __init__
    self.__scan_interval, MINIMUM_SCAN_INTERVAL, MINIMUM_SCAN_INTERVAL)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1407, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 181, in emit
    record, stack, _figure_out_source(record, stack, self.hass)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 97, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not datetime.timedelta
```

**Comment by sbressler** [comment]
I see tons of changes from @rsnodgrass in `device_tracker.py` in the past two months since the last release. Perhaps the latest release (1.0.6) doesn't work with the latest version of Home Assistant 0.109.3? I'll try my hand at installing tip of master and seeing if things start working... and here I was thinking I was saving time by figuring out HACS earlier tonight 😉

**Comment by sbressler** [comment]
Okay, just realized I can install master with HACS 🙏

**Comment by sbressler** [comment]
Working with tip of master! All my devices populated in the list of Entities. Feel free to resolve this after you create a new release?

**Comment by jrlucier** [comment]
Thanks for the quick triage!  I'm slacking on cutting a release.  Let me do a shakedown tonight with the latest version of HA and I'll cut one.  :)

**Comment by jrlucier** [comment]
Testing now, I'll cut a release if it all looks good in the morning.

**Comment by jrlucier** [comment]
1.0.7 is cut and released.  Great job on the updates @rsnodgrass !
