### ISSUE TITLE
HA 113.2 Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by cireflow** [jrlucier/eero_tracker#27]
******************
HA ver 113.2
python ver 3.8.3
host os HassOS 4.11
installation type Home Assistant OS
eero Mesh WiFi Device Tracker ver 1.0.7
******************

I just upgraded to HA 113.2 and now my log is flooded with the below error message:

2020-07-29 01:10:07 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/setup.py", line 161, in async_device_tracker_scan
    found_devices = await scanner.async_scan_devices()
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 482, in async_scan_devices
    return await self.hass.async_add_job(self.scan_devices)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eero_tracker/device_tracker.py", line 105, in scan_devices
    self._update_info()
  File "/config/custom_components/eero_tracker/device_tracker.py", line 119, in _update_info
    self.__account = self._account()
  File "/config/custom_components/eero_tracker/device_tracker.py", line 202, in _account
    return self._refreshed(lambda: self._get_req('account', cookies=self._cookie_dict))
  File "/config/custom_components/eero_tracker/device_tracker.py", line 172, in _refreshed
    return func()
  File "/config/custom_components/eero_tracker/device_tracker.py", line 202, in <lambda>
    return self._refreshed(lambda: self._get_req('account', cookies=self._cookie_dict))
  File "/config/custom_components/eero_tracker/device_tracker.py", line 236, in _get_req
    return self._parse_response(response)
  File "/config/custom_components/eero_tracker/device_tracker.py", line 222, in _parse_response
    data = json.loads(response.text)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

**Comment by jrlucier** [comment]
Upgrading locally... let me see if I can reproduce

**Comment by jrlucier** [comment]
Just pulled down Home Assistant 0.113.2, and everything is running fine...is it still erroring?

**Comment by cireflow** [comment]
I updated HACS and with the required restart the errors no longer happen.  Not sure if it was due to HACS update but we can close this issue.

Thank you for your quick response

Eric
